# Config for Player Visibility by xDesireRage
# The materials can be found here: http://goo.gl/qJVLlE
# You can get the colors from here: http://goo.gl/m6xrq2
PlayerVisibility:
# The item material when players are hide (material amount damage)
  itemON: REDSTONE_TORCH_ON 1 0
# The item when players are shown (material amount damage)
  itemOFF: LEVER 1 0
# The slot in inventory to get the item
  slot: 1
# This is the time in seconds until the player can click again
  timeDelay: 5
# This is the name of the item when players are shown
  displayNameON: '&2Players &7» &2Enabled'
# This is the name of the item when players are hidden
  displayNameOFF: '&2Players &7» &4Disabled'
# This is the world where the player gets the toggler
worldToGetItem:
  world: world
# The worlds where the plugin is enabled. ex: if a player has players disabled and joins world he will not see the players.
enabledWorlds:
  - world
  - hub
messages:
  consoleDeny: "&8[&6Visibility&8] &cYou cannot execute commands from console!"
  visibilityActivated: "&8[&6Visibility&8] &7You have toggled player visibility: &2on"
  visibilityDeactivated: "&8[&6Visibility&8] &7You have toggled player visibility: &4off"
  delay: "&8[&6Visibility&8] &cPlease wait &4%time% &cseconds before using the Torch!"
  noPerm: "&8[&6Visibility&8] &cYou don't have the permission to to this!"
  invalidCmd: "&8[&6Visibility&8] &cYou typed an invalid command."
  configReloaded: "&8[&6Visibility&8] &2Successfully reloaded config!"
  displayNameSet: "&8[&6Visibility&8] &2Display name %type% set to &8» %args%"
  messageSet: "&8[&6Visibility&8] &2Message %type% set to &8» %args%"
miscellaneous:
#On join, the player gets the torch
  joinTorch: true