#Config for Player Visibility by 1Tudor1
#The materials can be found here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
#You can get the colors from here: https://github.com/1Tudor1/GitHubPlugins/blob/master/ColorCodes_PlayerVisibility
# %timeDelay% is replaced with the time left to the next click
PlayerVisibility:
  itemMaterialON: REDSTONE_TORCH_ON
  itemMaterialOFF: LEVER
  amount: 1
  shrt: 0
  timeDelay: 5
  displayNameON: '&2Players &7>> &2Enabled'
  displayNameOFF: '&2Players &7>> &4Disabled'
worldToGetItem:
  world: hub
messages:
  visibilityActivated: '&8[&eVisibility&8] You have toggled player visibility: &2on'
  visibilityDeactivated: '&8[&eVisibility&8] You have toggled player visibility: &4off'
  timerMessage: '&ePlease wait %timeDelay% seconds before using the Torch!'
  noPermMessage: "&cYou don't have the permission to use the torch!"
miscellaneous:
  debug: false
#When pluginOn = true the player on join has the gamemode set to adventure and gets the torch
  pluginOn: true