name: PlayerVisibility
main: eu.playervisibility.main.PlayerVisibility
version: 1.2.15 Release
description: >
             This plugin enables/disables player visibility in the hub server.
commands:
    pv:
        description: Show the help of Player Visibility.
        aliases: [playervisibility]
        usage:  |
             /pv[hide,show,toolon/off,version,enable,disable,reload]
    pvversion:
        description: Show the help of Player Visibility.
        aliases: [playervisibilityversion]
        usage:  |
             Version of the plugin is 1.2.15 Release
    pvhide:
        aliases: [playervisibilityhide]
        description: Hide all the players.
    pvshow:
        aliases: [playervisibilityshow]
        description: Show all the players.
    pvtoolon:
        aliases: [playervisibilitytoolon]
        description: Give to the player the magic tool on.
    pvtooloff:
        aliases: [playervisibilitytooloff]
        description: Give to the player the magic tool off.
    pvenable:
        description: Activate the plugin.
    pvdisable:
        description: Deactivate the plugin.
    pvreload:
        description: Reload the plugin.
    setdisplaynameon:
        aliases: [setdpon, setdisplayon]
        description: Sets a new displayname when the torch is on.
    setdisplaynameoff:
        aliases: [setdpoff, setdisplayoff]
        description: Sets a new displayname when the torch is off.
    setmessage:
        aliases: [setm, setmsg]
        description: Sets a new message on any message of the plugin.