name: PlayerVisibility
main: eu.playervisibility.main.PlayerVisibility
version: 1.3.3 Release
description: This plugin enables/disables player visibility in the hub server.
authors: [1Tudor1, xDesireRage]
website: http://dev.bukkit.org/bukkit-plugins/player-visibilitytoggle/
commands:
    pv:
        description: Main Player Visibility command.
        aliases: [playervisibility]
permissions:
  pv.*:
    description: Gives access to all PlayerVisbility permissions
    children:
      pv.torch.hide: true
      pv.torch.show: true
      pv.tool: true
      pv.reload: true
      pv.setdisplayname: true
      pv.setmessage: true
      pv.bypass: true
      pv.nonHideable: true
  -pv.*:
    description: Deny access to all PlayerVisbility permissions
    children:
      pv.torch.hide: false
      pv.torch.show: false
      pv.tool: false
      pv.reload: false
      pv.setdisplayname: false
      pv.setmessage: false
      pv.bypass: false
      pv.denypick: true
      pv.denydrop: true
      pv.denybreak: true
      pv.denyplace: true
      pv.nonHideable: false
  pv.torch.hide:
    description: You can hide the players with command.
    default: true
  pv.torch.show:
    description: You can show the players with command.
    default: true
  pv.tool:
    description: You get the tool for hidden players.
    default: op
  pv.reload:
    description: You cand reload the plugin config.
    default: op
  pv.setdisplayname:
    description: Set the disaplay name for the toggleoff item.
    default: op
  pv.setmessage:
    description: Set any message of the plugin.
    default: op
  pv.torch.use:
    description: Allow the player to use the torch.
    default: true
    children:
      pv.torch.hide: true
      pv.torch.show: true
  pv.bypass:
    description: Players bypasses the time between clicks.
    default: op
  pv.nonHideable:
    description: Player is hidable and other players can see him.
    default: op